### ISSUE TITLE
Support various spellings and locations for the `janitor.json` config file

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/c9.ide.janitorconfig#1]
I think it would be valuable to support these following locations:
- [x] `./janitor.json` (directly inside the Cloud9 workspace, so that projects can commit their own `janitor.json` file in their repositories)
- [x] `~/janitor.json` (fallback)

And also the following alternative spellings for the file name:
- [x] `janitor.json`
- [x] `.janitor.json`

@nt1m What do you think?

**Comment by nt1m** [comment]
Sounds good.
