### ISSUE TITLE
No run configurations even though janitor.json scripts are "loaded"

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/c9.ide.janitorconfig#3]
When I spawn a Janitor container on https://janitor.technology I see that the `c9.ide.janitorconfig` plugin is loaded, and it says it has loaded all `janitor.json` scripts, but the `Run` button still has no run configurations associated to it:

![janitor-json-fail](https://user-images.githubusercontent.com/599268/28708984-94dd97b6-737e-11e7-9c59-fdbd039d179c.png)

**Comment by jankeromnes** [comment]
Same thing for Servo:

![janitor-json-fail2](https://user-images.githubusercontent.com/599268/28709143-441fd7a2-737f-11e7-8c5a-3e3bf84aaf3a.png)

**Comment by nt1m** [comment]
Hmm, odd. Taking a look

**Comment by nt1m** [comment]
Oddly, the runners reappear after reloading the IDE.
