### ISSUE TITLE
Loading Run configurations from janitor.json sometimes fails

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/c9.ide.janitorconfig#4]
When loading a Cloud9 IDE window for a Janitor project, very often the console says that the plugin managed to load its `janitor.json` file successfully, but the `Run` button has no run configurations.

Refreshing the IDE sometimes fixes this issue. @nt1m were you able to get a review of the Run config loading mechanism from the Cloud9 SDK community?

**Comment by nt1m** [comment]
There are actually 2 commits trying to fix this: 83be5ebfcf870adf95c1add2029cf91d83770494 and a57b91d03e4a39c23f766def14ae5605f50d9f08

> were you able to get a review of the Run config loading mechanism from the Cloud9 SDK community?

According to Harutyun, the way I currently do it (setJson) should work fine: https://groups.google.com/forum/#!topic/cloud9-sdk/Z90iOt-jyo8

but it doesn't unfortunately.

**Comment by jankeromnes** [comment]
We've been wondering if this issue was gone, but yesterday when I spawned new containers for all 9 Janitor projects, 2 or 3 containers had this bug on first IDE load:

![run-button-bug](https://user-images.githubusercontent.com/599268/33363018-d7f891c4-d4de-11e7-9455-180f4e849f94.png)

But since it's become less frequent, I'll rename the issue title to "sometimes".

**Comment by jankeromnes** [comment]
This seems to work pretty well now. Closing.
